# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tbae <tbae@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/14 12:55:59 by tbae              #+#    #+#              #
#    Updated: 2023/07/27 12:44:48 by tbae             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC =	ft_strlen.c ft_isalpha.c ft_isalnum.c ft_isascii.c\
		ft_isdigit.c ft_isprint.c ft_memset.c ft_bzero.c\
		ft_memcpy.c ft_memmove.c ft_strlcpy.c ft_strlcat.c\
		ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c\
		ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c\
		ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c\
		ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c\
		ft_strmapi.c ft_striteri.c ft_putchar_fd.c\
		ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c\
		ft_printf.c char_or_str.c hexadecimal.c decimal.c\
		pointer.c get_next_line.c get_next_line_utils.c\

OBJ = ${SRC:.c=.o}
NAME = libft.a
CC = cc
RM = rm -f

${NAME}: ${OBJ}
	ar rcs ${NAME} ${OBJ}

all : ${NAME}

clean :
	${RM} ${OBJ}

fclean : clean
	${RM} ${NAME}

re : fclean all

.PHONY : all clean fclean re
